import { Alert, AlertTitle, IconButton, Box } from '@mui/material'
import CloseIcon from '@mui/icons-material/Close'
import { SmartToy as SmartToyIcon } from '@mui/icons-material'
import useAIDisclosureStore from '../../stores/aiDisclosureStore'

/**
 * Texto de divulgacion por defecto exigido por el Articulo 50(1) del EU AI Act.
 * No se debe abreviar ni suavizar: debe informar claramente de que el sistema
 * usa IA y de que los resultados requieren revision humana.
 */
export const DEFAULT_AI_DISCLOSURE_MESSAGE =
  'This system uses AI-powered analysis. Results are generated by automated tools and should be reviewed by qualified personnel.'

export interface DisclosureBannerProps {
  /**
   * Mensaje de divulgacion. Por defecto usa el texto conforme al Art. 50(1).
   * Permite personalizarlo para paginas con contexto especifico (p. ej. un
   * flujo de generacion de tests puede aclarar "Generacion automatica de tests").
   */
  message?: string
  /** Titulo opcional del aviso. Por defecto "AI Transparency". */
  title?: string
}

/**
 * Banner reutilizable de divulgacion de IA (EU AI Act, Articulo 50(1)).
 *
 * Sutil pero visible, no bloqueante y descartable por sesion (sessionStorage).
 * Insertar este componente en cualquier pagina que exponga funcionalidades de IA
 * (generacion de tests, analisis de vulnerabilidades, self-healing, etc.).
 */
export default function DisclosureBanner({
  message = DEFAULT_AI_DISCLOSURE_MESSAGE,
  title = 'AI Transparency',
}: DisclosureBannerProps) {
  const dismissed = useAIDisclosureStore((state) => state.dismissed)
  const dismiss = useAIDisclosureStore((state) => state.dismiss)

  if (dismissed) {
    return null
  }

  return (
    <Box sx={{ mb: 2 }} data-testid="ai-disclosure-banner">
      <Alert
        severity="info"
        role="status"
        icon={<SmartToyIcon />}
        action={
          <IconButton
            aria-label="Dismiss AI disclosure"
            color="inherit"
            size="small"
            onClick={dismiss}
          >
            <CloseIcon fontSize="inherit" />
          </IconButton>
        }
        sx={{
          alignItems: 'flex-start',
          '& .MuiAlert-message': { width: '100%' },
        }}
      >
        <AlertTitle sx={{ fontWeight: 600 }}>{title}</AlertTitle>
        {message}
      </Alert>
    </Box>
  )
}
